import os
import pickle
import joblib
from sklearn.neighbors import NearestNeighbors

# --- Configuration ---
ASSETS_DIR = "./assets"


def build_retrieval_index():
    print("🚀 Building Retrieval Index (KNN)...")

    # 1. Load the Sparse Matrix generated by data_preprocess.py
    matrix_path = os.path.join(ASSETS_DIR, "tfidf_benchmark_matrix.pkl")
    print(f"Loading benchmark matrix from {matrix_path}...")

    with open(matrix_path, 'rb') as f:
        benchmark_matrix = pickle.load(f)

    print(f"Matrix shape: {benchmark_matrix.shape}")

    # 2. Initialize and Fit the KNN Model
    # We use 'cosine' distance because it evaluates the angle/overlap between high-dimensional
    # sparse vectors perfectly, ignoring magnitude differences.
    # The 'brute' algorithm is the most memory-efficient and fastest approach for sparse matrices.
    print("Fitting Nearest Neighbors index...")
    knn = NearestNeighbors(n_neighbors=15, metric='cosine', algorithm='brute')
    knn.fit(benchmark_matrix)

    # 3. Save the Index to Disk
    output_path = os.path.join(ASSETS_DIR, "knn_retrieval_index.joblib")
    print(f"💾 Saving KNN model to {output_path}...")
    joblib.dump(knn, output_path)

    print("✅ Indexing complete! The model is ready for runtime candidate generation.")


if __name__ == "__main__":
    build_retrieval_index()
