import xgboost as xgb
import pandas as pd
import joblib
import os
import time
import matplotlib.pyplot as plt
import scipy.sparse as sp
from sklearn.model_selection import train_test_split

# Paths
INPUT_DIR = "./processed_data"
MODEL_DIR = "./saved_model"


def train_model():
    print("Loading Training Data from disk...")
    start_time = time.time()

    # Load the 80% training asset generated by feature engineering
    X_train_full = pd.read_pickle(f"{INPUT_DIR}/X_train.pkl")
    y_train_full = pd.read_pickle(f"{INPUT_DIR}/y_train.pkl")
    w_train_full = pd.read_pickle(f"{INPUT_DIR}/w_train.pkl")

    le = joblib.load(f"{INPUT_DIR}/label_encoder.joblib")
    print(f"Data loaded in {time.time() - start_time:.2f} seconds.")

    # =========================================================
    # STEP 1: SPLIT TRAIN SET INTO TRAIN & VALIDATION SETS
    # =========================================================
    # Splitting 15% of the training data out to serve as the validation set
    print("\nSplitting X_train into internal Train and Validation sets...")
    X_train, X_val, y_train, y_val, w_train, w_val = train_test_split(
        X_train_full, y_train_full, w_train_full,
        test_size=0.15,
        random_state=42
    )

    print(f" -> Internal Train Matrix Shape: {X_train.shape}")
    print(f" -> Internal Valid Matrix Shape: {X_val.shape}")
    print(f" -> Target Classes: {len(le.classes_)} unique jobs")

    print("\nConverting Pandas Sparse DataFrames to SciPy CSR Matrices to prevent RAM blowout...")
    # This securely transitions the data into the exact mathematical format XGBoost needs
    X_train_csr = X_train.sparse.to_coo().tocsr()
    X_val_csr = X_val.sparse.to_coo().tocsr()
    print("Conversion successful! Data is ready for the GPU.")

    # =========================================================
    # STEP 2: INITIALIZE CLASSIFIER WITH MONITORING METRICS
    # =========================================================
    print("\nInitializing XGBoost Classifier on GPU...")
    model = xgb.XGBClassifier(
        n_estimators=150,
        learning_rate=0.1,
        max_depth=6,
        objective='multi:softprob',
        num_class=len(le.classes_),
        tree_method='hist',
        device='cuda',
        # 'mlogloss' = Multi-class Log Loss
        # 'merror'   = Multi-class Classification Error Rate (Error = 1 - Accuracy)
        eval_metric=['mlogloss', 'merror'],
        early_stopping_rounds=15,
        random_state=42,
        n_jobs=-1
    )

    # =========================================================
    # STEP 3: FIT THE MODEL WITH LIVE MONITORING
    # =========================================================
    print("\nFitting model (Monitoring Log Loss and Error Rate)...")
    train_start = time.time()

    model.fit(
        X_train_csr, y_train,
        sample_weight=w_train,
        eval_set=[(X_train_csr, y_train), (X_val_csr, y_val)],
        sample_weight_eval_set=[w_train, w_val],
        verbose=5
    )

    print(f"\nXGBoost Training Complete in {time.time() - train_start:.2f} seconds!")

    # Save the trained model
    os.makedirs(MODEL_DIR, exist_ok=True)
    model_path = os.path.join(MODEL_DIR, "career_expert_xgboost.json")
    model.save_model(model_path)
    print(f"Model successfully saved to: {model_path}")

    # =========================================================
    # STEP 4: VISUAL MONITORING (PLOT THE LEARNING CURVES)
    # =========================================================
    print("\nGenerating Learning Curve Graphs...")
    results = model.evals_result()
    epochs = len(results['validation_0']['mlogloss'])
    x_axis = range(0, epochs)

    # Calculate accuracy from error rates (Accuracy = 1 - Error Rate)
    train_accuracy = [1.0 - err for err in results['validation_0']['merror']]
    val_accuracy = [1.0 - err for err in results['validation_1']['merror']]

    fig, ax = plt.subplots(1, 2, figsize=(14, 5))

    # Plot 1: Multi-Class Log Loss
    ax[0].plot(x_axis, results['validation_0']['mlogloss'], label='Train Loss', color='blue', linewidth=2)
    ax[0].plot(x_axis, results['validation_1']['mlogloss'], label='Validation Loss', color='orange', linewidth=2)
    ax[0].legend()
    ax[0].set_title('XGBoost Multi-Class Log Loss')
    ax[0].set_xlabel('Boosting Round (Trees)')
    ax[0].set_ylabel('Log Loss')
    ax[0].grid(True, linestyle='--', alpha=0.5)

    # Plot 2: Accuracy Curve
    ax[1].plot(x_axis, train_accuracy, label='Train Accuracy', color='blue', linewidth=2)
    ax[1].plot(x_axis, val_accuracy, label='Validation Accuracy', color='orange', linewidth=2)
    ax[1].legend()
    ax[1].set_title('XGBoost Multi-Class Accuracy')
    ax[1].set_xlabel('Boosting Round (Trees)')
    ax[1].set_ylabel('Accuracy Rate (0.0 to 1.0)')
    ax[1].grid(True, linestyle='--', alpha=0.5)

    # Save graph to disk
    plot_path = os.path.join(MODEL_DIR, "training_learning_curves.png")
    plt.tight_layout()
    plt.savefig(plot_path, dpi=300)
    print(f"Learning curves successfully saved to: {plot_path}")


if __name__ == "__main__":
    train_model()
